version: "3.2"
services:
   functions-emulator:
      image: santhoshsram/functions-emulator:0.1
      ports:
         - "8008:8008"
         - "8010:8010"
      volumes:
         - type: bind
           source: /Users/santhosh/OneDrive/workspace
           target: /workspace
           read_only: true
